### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by ToddyTheNoobDud** [devstacking/RCOOL#1]
### Bugs:
FStringGameMenuChromeForcedUserIds Is missing a , on value

FStringVoiceBetaBadgeLearnMoreLink Is missing a , on value

### Solutions

  "FStringGameMenuChromeForcedUserIds": "1",
  
  "FStringVoiceBetaBadgeLearnMoreLink": "null",

**Comment by vsvpp** [comment]
ok
